CREATE TABLE mascota(
  id bigint(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(30) NOT NULL,
  idtipo INT NOT NULL
);

CREATE TABLE tipo(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  descripcion VARCHAR(30) NOT NULL
);

ALTER TABLE mascota ADD CONSTRAINT fk_tipo_mascota FOREIGN KEY (idtipo) REFERENCES tipo (id) ON UPDATE CASCADE;